# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-case-conflict
      - id: fix-encoding-pragma
      - id: check-added-large-files
        args: ["--maxkb=128"]
  - repo: https://github.com/ambv/black
    rev: "23.1.0"
    hooks:
      - id: black
        language: python
        types: [python]
        args: ["--target-version=py310", "--line-length=160"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
