[build-system]
requires = ["setuptools", "setuptools-scm", "cffi"]
build-backend = "setuptools.build_meta"

[project]
name = "lib7zip"
version = "0.2.0"
dependencies = ["cffi"]

[tool.setuptools]
packages = ["lib7zip"]

[tool.isort]
profile = "black"
